### PR TITLE
Reorganising benchnark repo

### PR DESCRIPTION
**Pull request by bam241**
I have been trying to modify the organization of the benchmark repo according to what has been decided in during the last benchmark meeting:
- use the master branch as an generic definition of the OFCB benchmark 
- use the CYclus branch to host the different input for the OFCB (and other) benchmark, as well as the cyclus/json conversion tool,

The master branch should containing only the canonical description of the different tests and the link to the different file/website used in the context of the OFCB

Let me know what you think about it :)

BaM

### CODE REVIEW

**Comment by scopatz** [comment]
What is with the hidden readme directory?

**Comment by scopatz** [comment]
Just curious :)

**Comment by Baaaaam** [comment]
I put it to host the formula image... There is maybe a better way to do it...

**Comment by scopatz** [comment]
I would put them in a top-level, visible (ie non-hidden) directory that is called `static/` or `img/` or something. They aren't really a readme themselves and there is no reason to obscure there existence. My two rand.

**Comment by Baaaaam** [comment]
@scopatz, done

**Comment by scopatz** [comment]
Thanks

**Pull request merged**
